[dependencies]
clap = "2.33.3"
image = "0.23.10"
visioncortex = { git = "https://github.com/mattjames-canva/visioncortex.git" }
fastrand = "1.8"
pyo3 = { version = "0.19.0", optional = true }

[features] 